"""
This type stub file was generated by pyright.
"""

from typing import Tuple
from modi_plus.module.module import OutputModule

"""Motor module."""
class Motor(OutputModule):
    PROPERTY_MOTOR_STATE = ...
    PROPERTY_MOTOR_SPEED = ...
    PROPERTY_MOTOR_ANGLE = ...
    PROPERTY_MOTOR_ANGLE_APPEND = ...
    PROPERTY_MOTOR_STOP = ...
    PROPERTY_OFFSET_CURRENT_ANGLE = ...
    PROPERTY_OFFSET_CURRENT_SPEED = ...
    PROPERTY_OFFSET_TARGET_ANGLE = ...
    PROPERTY_OFFSET_TARGET_SPEED = ...
    @property
    def angle(self) -> int:
        """Returns current angle

        :return: Current angle value
        :rtype: int
        """
        ...
    
    @angle.setter
    def angle(self, angle_value: Tuple[int, int]) -> None:
        """Sets the angle of the motor

        :param angle_value: Value of angle and speed to reach target angle
        :type angle_value: Tuple[int, int]
        :return: None
        """
        ...
    
    @property
    def target_angle(self) -> int:
        """Returns target angle

        :return: Target angle value
        :rtype: int
        """
        ...
    
    @property
    def speed(self) -> int:
        """Returns current speed

        :return: Current speed value
        :rtype: int
        """
        ...
    
    @speed.setter
    def speed(self, target_speed: int) -> None:
        """Sets the speed of the motor

        :param target_speed: Speed to set the motor.
        :type target_speed: int
        :return: None
        """
        ...
    
    @property
    def target_speed(self) -> int:
        """Returns target speed

        :return: Target speed value
        :rtype: int
        """
        ...
    
    def set_angle(self, target_angle: int, target_speed: int = ...) -> None:
        """Sets the angle of the motor

        :param target_angle: Angle to set the motor.
        :type target_angle: int
        :param target_speed: Speed to reach target angle.
        :type target_speed: int
        :return: None
        """
        ...
    
    def set_speed(self, target_speed: int) -> None:
        """Sets the speed of the motor

        :param target_speed: Speed to set the motor.
        :type target_speed: int
        :return: None
        """
        ...
    
    def append_angle(self, target_angle: int, target_speed: int = ...) -> None:
        """append the angle form current angle of the motor

        :param target_angle: Angle to append the motor angle.
        :type target_angle: int
        :param target_speed: Speed to reach target angle.
        :type target_speed: int
        :return: None
        """
        ...
    
    def stop(self) -> None:
        """Stop operating motor

        :return: None
        """
        ...
    


