"""
This type stub file was generated by pyright.
"""

from modi_plus.module.module import SetupModule

"""Battery module."""
class Battery(SetupModule):
    PROPERTY_BATTERY_STATE = ...
    PROPERTY_OFFSET_LEVEL = ...
    @property
    def level(self) -> float:
        """Returns the level value

        :return: The battery's level.
        :rtype: float
        """
        ...
    


