"""
This type stub file was generated by pyright.
"""

from modi_plus import about
from modi_plus.modi_plus import MODIPlus

"""Top-level package for pyMODI+."""
__all__ = ["MODIPlus"]
__version__ = ...
