"""
This type stub file was generated by pyright.
"""

import threading as th

class ExeThread(th.Thread):
    """
    :param dict() modules: dict() of module instance
    """
    def __init__(self, modules, connection_task) -> None:
        ...
    
    def close(self): # -> None:
        ...
    
    def run(self) -> None:
        """ Run executor task

        :return: None
        """
        ...
    


