"""
This type stub file was generated by pyright.
"""

from modi_plus.module.setup_module.network import Network
from modi_plus.module.setup_module.battery import Battery
from modi_plus.module.input_module.env import Env
from modi_plus.module.input_module.imu import Imu
from modi_plus.module.input_module.button import Button
from modi_plus.module.input_module.dial import Dial
from modi_plus.module.input_module.joystick import Joystick
from modi_plus.module.input_module.tof import Tof
from modi_plus.module.output_module.display import Display
from modi_plus.module.output_module.motor import Motor
from modi_plus.module.output_module.led import Led
from modi_plus.module.output_module.speaker import Speaker
from modi_plus.module.module import ModuleList

"""Main MODI+ module."""
class MODIPlus:
    network_uuids = ...
    def __call__(cls, *args, **kwargs):
        ...
    
    def __init__(self, connection_type=..., verbose=..., port=..., network_uuid=...) -> None:
        ...
    
    def open(self): # -> None:
        ...
    
    def close(self): # -> None:
        ...
    
    def send(self, message): # -> None:
        """Low level method to send json pkt directly to modules

        :param message: Json packet to send
        :return: None
        """
        ...
    
    def recv(self): # -> Any:
        """Low level method to receive json pkt directly from modules

        :return: Json msg received
        :rtype: str if msg exists, else None
        """
        ...
    
    def network(self, id: int) -> Network:
        """Module Class of connected Network module.
        """
        ...
    
    def battery(self, id: int) -> Battery:
        """Module Class of connected Battery module.
        """
        ...
    
    def env(self, id: int) -> Env:
        """Module Class of connected Environment modules.
        """
        ...
    
    def imu(self, id: int) -> Imu:
        """Module Class of connected IMU modules.
        """
        ...
    
    def button(self, id: int) -> Button:
        """Module Class of connected Button modules.
        """
        ...
    
    def dial(self, id: int) -> Dial:
        """Module Class of connected Dial modules.
        """
        ...
    
    def joystick(self, id: int) -> Joystick:
        """Module Class of connected Joystick modules.
        """
        ...
    
    def tof(self, id: int) -> Tof:
        """Module Class of connected ToF modules.
        """
        ...
    
    def display(self, id: int) -> Display:
        """Module Class of connected Display modules.
        """
        ...
    
    def motor(self, id: int) -> Motor:
        """Module Class of connected Motor modules.
        """
        ...
    
    def led(self, id: int) -> Led:
        """Module Class of connected Led modules.
        """
        ...
    
    def speaker(self, id: int) -> Speaker:
        """Module Class of connected Speaker modules.
        """
        ...
    
    @property
    def modules(self) -> ModuleList:
        """Module List of connected modules except network module.
        """
        ...
    
    @property
    def networks(self) -> ModuleList:
        """Module List of connected Network modules.
        """
        ...
    
    @property
    def batterys(self) -> ModuleList:
        """Module List of connected Battery modules.
        """
        ...
    
    @property
    def envs(self) -> ModuleList:
        """Module List of connected Environment modules.
        """
        ...
    
    @property
    def imus(self) -> ModuleList:
        """Module List of connected IMU modules.
        """
        ...
    
    @property
    def buttons(self) -> ModuleList:
        """Module List of connected Button modules.
        """
        ...
    
    @property
    def dials(self) -> ModuleList:
        """Module List of connected Dial modules.
        """
        ...
    
    @property
    def joysticks(self) -> ModuleList:
        """Module List of connected Joystick modules.
        """
        ...
    
    @property
    def tofs(self) -> ModuleList:
        """Module List of connected ToF modules.
        """
        ...
    
    @property
    def displays(self) -> ModuleList:
        """Module List of connected Display modules.
        """
        ...
    
    @property
    def motors(self) -> ModuleList:
        """Module List of connected Motor modules.
        """
        ...
    
    @property
    def leds(self) -> ModuleList:
        """Module List of connected Led modules.
        """
        ...
    
    @property
    def speakers(self) -> ModuleList:
        """Module List of connected Speaker modules.
        """
        ...
    


