"""
This type stub file was generated by pyright.
"""

class ExeTask:
    def __init__(self, modules, connection_task) -> None:
        ...
    
    def run(self, delay): # -> None:
        """ Run in ExecutorThread

        :param delay: time value to wait in seconds
        :type delay: float
        """
        ...
    


