"""
This type stub file was generated by pyright.
"""

from modi_plus.module.module import InputModule

"""Button module."""
class Button(InputModule):
    STATE_TRUE = ...
    STATE_FALSE = ...
    PROPERTY_BUTTON_STATE = ...
    PROPERTY_OFFSET_CLICKED = ...
    PROPERTY_OFFSET_DOUBLE_CLICKED = ...
    PROPERTY_OFFSET_PRESSED = ...
    PROPERTY_OFFSET_TOGGLED = ...
    @property
    def clicked(self) -> bool:
        """Returns true when button is clicked

        :return: `True` if clicked or `False`.
        :rtype: bool
        """
        ...
    
    @property
    def double_clicked(self) -> bool:
        """Returns true when button is double clicked

        :return: `True` if double clicked or `False`.
        :rtype: bool
        """
        ...
    
    @property
    def pressed(self) -> bool:
        """Returns true while button is pressed

        :return: `True` if pressed or `False`.
        :rtype: bool
        """
        ...
    
    @property
    def toggled(self) -> bool:
        """Returns true when button is toggled

        :return: `True` if toggled or `False`.
        :rtype: bool
        """
        ...
    


