"""
This type stub file was generated by pyright.
"""

from modi_plus.module.module import InputModule

"""Dial module."""
class Dial(InputModule):
    PROPERTY_DIAL_STATE = ...
    PROPERTY_OFFSET_TURN = ...
    PROPERTY_OFFSET_SPEED = ...
    @property
    def turn(self) -> int:
        """Returns the angle of the dial between 0 and 100

        :return: The dial's angle.
        :rtype: int
        """
        ...
    
    @property
    def speed(self) -> int:
        """Returns the turn speed of the dial between -100 and 100

        :return: The dial's turn speed.
        :rtype: int
        """
        ...
    


