"""
This type stub file was generated by pyright.
"""

from modi_plus.module.module import InputModule

"""Env module."""
class Env(InputModule):
    PROPERTY_ENV_STATE = ...
    PROPERTY_OFFSET_ILLUMINANCE = ...
    PROPERTY_OFFSET_TEMPERATURE = ...
    PROPERTY_OFFSET_HUMIDITY = ...
    PROPERTY_OFFSET_VOLUME = ...
    @property
    def illuminance(self) -> int:
        """Returns the value of illuminance between 0 and 100

        :return: The environment's illuminance.
        :rtype: int
        """
        ...
    
    @property
    def temperature(self) -> int:
        """Returns the value of temperature between -10 and 60

        :return: The environment's temperature.
        :rtype: int
        """
        ...
    
    @property
    def humidity(self) -> int:
        """Returns the value of humidity between 0 and 100

        :return: The environment's humidity.
        :rtype: int
        """
        ...
    
    @property
    def volume(self) -> int:
        """Returns the value of volume between 0 and 100

        :return: The environment's volume.
        :rtype: int
        """
        ...
    


