"""
This type stub file was generated by pyright.
"""

from typing import Tuple
from modi_plus.module.module import InputModule

"""Imu module."""
class Imu(InputModule):
    PROPERTY_ANGLE_STATE = ...
    PROPERTY_ACC_STATE = ...
    PROPERTY_GYRO_STATE = ...
    PROPERTY_VIBRATION_STATE = ...
    PROPERTY_OFFSET_ROLL = ...
    PROPERTY_OFFSET_PITCH = ...
    PROPERTY_OFFSET_YAW = ...
    PROPERTY_OFFSET_ACC_X = ...
    PROPERTY_OFFSET_ACC_Y = ...
    PROPERTY_OFFSET_ACC_Z = ...
    PROPERTY_OFFSET_GYRO_X = ...
    PROPERTY_OFFSET_GYRO_Y = ...
    PROPERTY_OFFSET_GYRO_Z = ...
    PROPERTY_OFFSET_VIBRATION = ...
    @property
    def angle_x(self) -> float:
        """Returns the angle_x angle of the imu

        :return: The imu's angle_x angle.
        :rtype: float
        """
        ...
    
    @property
    def angle_y(self) -> float:
        """Returns the angle_y angle of the imu

        :return: The imu's angle_y angle.
        :rtype: float
        """
        ...
    
    @property
    def angle_z(self) -> float:
        """Returns the angle_zle_z angle of the imu

        :return: The imu's angle_z angle.
        :rtype: float
        """
        ...
    
    @property
    def angle(self) -> Tuple[float, float, float]:
        """Returns the angle_x, angle_y and angle_z angle of the imu

        :return: The imu's angles of angle_x, angle_y and angle_z.
        :rtype: tuple
        """
        ...
    
    @property
    def angular_vel_x(self) -> float:
        """Returns the angle_x angle of the imu

        :return: The imu's angular velocity the about x-axis.
        :rtype: float
        """
        ...
    
    @property
    def angular_vel_y(self) -> float:
        """Returns the angular velocity about y-axis

        :return: The imu's angular velocity the about y-axis.
        :rtype: float
        """
        ...
    
    @property
    def angular_vel_z(self) -> float:
        """Returns the angular velocity about z-axis

        :return: The imu's angular velocity the about z-axis.
        :rtype: float
        """
        ...
    
    @property
    def angular_velocity(self) -> Tuple[float, float, float]:
        """Returns the angular velocity about x, y and z axis

        :return: The imu's angular velocity the about x, y and z axis.
        :rtype: tuple
        """
        ...
    
    @property
    def acceleration_x(self) -> float:
        """Returns the x component of the acceleration

        :return: The imu's x-axis acceleration.
        :rtype: float
        """
        ...
    
    @property
    def acceleration_y(self) -> float:
        """Returns the y component of the acceleration

        :return: The imu's y-axis acceleration.
        :rtype: float
        """
        ...
    
    @property
    def acceleration_z(self) -> float:
        """Returns the z component of the acceleration

        :return: The imu's z-axis acceleration.
        :rtype: float
        """
        ...
    
    @property
    def acceleration(self) -> Tuple[float, float, float]:
        """Returns the acceleration about x, y and z axis

        :return: The imu's acceleration the about x, y and z axis.
        :rtype: tuple
        """
        ...
    
    @property
    def vibration(self) -> float:
        """Returns the vibration value

        :return: The imu's vibration.
        :rtype: float
        """
        ...
    


