"""
This type stub file was generated by pyright.
"""

from modi_plus.module.module import InputModule

"""Joystick module."""
class Joystick(InputModule):
    STATE_UP = ...
    STATE_DOWN = ...
    STATE_LEFT = ...
    STATE_RIGHT = ...
    STATE_ORIGIN = ...
    PROPERTY_POSITION_STATE = ...
    PROPERTY_DIRECTION_STATE = ...
    PROPERTY_OFFSET_X = ...
    PROPERTY_OFFSET_Y = ...
    PROPERTY_OFFSET_DIRECTION = ...
    @property
    def x(self) -> int:
        """Returns the x position of the joystick between -100 and 100

        :return: The joystick's x position.
        :rtype: int
        """
        ...
    
    @property
    def y(self) -> int:
        """Returns the y position of the joystick between -100 and 100

        :return: The joystick's y position.
        :rtype: int
        """
        ...
    
    @property
    def direction(self) -> str:
        """Returns the direction of the joystick

        :return: 'up', 'down', 'left', 'right', 'origin'
        :rtype: str
        """
        ...
    


