"""
This type stub file was generated by pyright.
"""

from modi_plus.module.module import InputModule

"""Tof module."""
class Tof(InputModule):
    PROPERTY_DISTANCE_STATE = ...
    PROPERTY_OFFSET_DISTANCE = ...
    @property
    def distance(self) -> float:
        """Returns the distance of the object between 0cm and 100cm

        :return: The tof's distance to object.
        :rtype: float
        """
        ...
    


