"""
This type stub file was generated by pyright.
"""

from typing import List

def list_modi_ports() -> List[str]:
    """Returns a list of connected MODI ports

    :return: List[ListPortInfo]
    """
    ...

def is_on_pi() -> bool:
    """Returns whether connected to pi

    :return: true if connected to pi
    :rtype: bool
    """
    ...

def is_network_module_connected() -> bool:
    """Returns whether network module is connected

    :return: true if connected
    :rtype: bool
    """
    ...

def ask_modi_device(devices):
    ...

def get_platform(): # -> LiteralString | Literal['rpi', 'chrome']:
    ...

def get_ble_task_path(): # -> str | None:
    ...

class MODIConnectionError(Exception):
    ...


