"""
This type stub file was generated by pyright.
"""

import threading as th

class StoppableThread(th.Thread):
    def __init__(self, module, method) -> None:
        ...
    
    def stop(self): # -> None:
        ...
    
    def stopped(self): # -> bool:
        ...
    
    def run(self):
        ...
    


class Inspector:
    """
    Inspector diagnoses malfunctioning modules (all modules but network)
    """
    row_len = ...
    def __init__(self) -> None:
        ...
    
    @staticmethod
    def clear(): # -> None:
        ...
    
    def print_wrap(self, msg): # -> None:
        ...
    
    def print_module_page(self, module, i, nb_modules): # -> None:
        ...
    
    def inspect(self, module, i, nb_modules): # -> None:
        ...
    
    def inspect_battery(self, module, i, nb_modules): # -> None:
        ...
    
    def inspect_env(self, module, i, nb_modules): # -> None:
        ...
    
    def inspect_imu(self, module, i, nb_modules): # -> None:
        ...
    
    def inspect_button(self, module, i, nb_modules): # -> None:
        ...
    
    def inspect_dial(self, module, i, nb_modules): # -> None:
        ...
    
    def inspect_joystick(self, module, i, nb_modules): # -> None:
        ...
    
    def inspect_tof(self, module, i, nb_modules): # -> None:
        ...
    
    def inspect_display(self, module, i, nb_modules): # -> None:
        ...
    
    def inspect_motor(self, module, i, nb_modules): # -> None:
        ...
    
    def inspect_led(self, module, i, nb_modules): # -> None:
        ...
    
    def inspect_speaker(self, module, i, nb_modules): # -> None:
        ...
    
    def run_inspection(self): # -> None:
        ...
    


