"""
This type stub file was generated by pyright.
"""

from typing import Optional, Tuple

def parse_get_property_message(destination_id: int, property_type: int, property_frequency: int): # -> str:
    ...

def parse_set_property_message(destination_id: int, property_type: int, property_values: Tuple): # -> str:
    ...

def parse_message(command: int, source: int, destination: int, byte_data: Tuple = ...): # -> str:
    ...

def decode_message(message: str): # -> tuple[str, str, str, str, str]:
    ...

def unpack_data(data: str, structure: Tuple = ...): # -> list[Any]:
    ...

def parse_data(values, data_type: str) -> Optional[Tuple]:
    ...

def decode_data(data: str) -> float:
    ...

