"""
This type stub file was generated by pyright.
"""

class Tutor:
    """
    Tutor teaches overall usage of PyMODI+
    """
    row_len = ...
    def __init__(self) -> None:
        ...
    
    @staticmethod
    def clear(): # -> None:
        ...
    
    def print_wrap(self, msg): # -> None:
        ...
    
    def print_lesson(self, lesson, title): # -> None:
        ...
    
    @staticmethod
    def check_user_input(answer, give_answer=..., guide=...): # -> str:
        ...
    
    def run_introduction(self): # -> None:
        ...
    
    def run_lesson1(self):
        ...
    
    def run_lesson2(self):
        ...
    
    def run_lesson3(self):
        ...
    
    def run_lesson4(self):
        ...
    


