"""
This type stub file was generated by pyright.
"""

class UsageInstructor:
    """
    Usage Instructor teaches basic module usage of PyMODI+.
    It mainly teachs what methods are available for each module.
    """
    row_len = ...
    def __init__(self) -> None:
        ...
    
    @staticmethod
    def clear(): # -> None:
        ...
    
    def print_wrap(self, msg): # -> None:
        ...
    
    def print_topic(self, module_type): # -> None:
        ...
    
    def run_usage_manual(self): # -> None:
        ...
    
    def exit(self):
        ...
    
    def run_button_manual(self): # -> None:
        ...
    
    def run_dial_manual(self): # -> None:
        ...
    
    def run_env_manual(self): # -> None:
        ...
    
    def run_imu_manual(self): # -> None:
        ...
    
    def run_joystick_manual(self): # -> None:
        ...
    
    def run_tof_manual(self): # -> None:
        ...
    
    def run_display_manual(self): # -> None:
        ...
    
    def run_led_manual(self): # -> None:
        ...
    
    def run_motor_manual(self): # -> None:
        ...
    
    def run_speaker_manual(self): # -> None:
        ...
    


